import type {CatalogueComponent, ComponentCatalogue} from '../../src/types/componentCatalogue.types.ts'

const cell = (values: string[]): string => values.length > 0 ? values.join('<br>') : '—'

const exportLabel = (component: CatalogueComponent): string[] =>
  component.exports.map((item) => `${item.kind}: ${item.name} (${item.module})`)

export const renderManifest = (catalogue: ComponentCatalogue): string =>
  `${JSON.stringify(catalogue, null, 2)}\n`

export const renderMarkdown = (catalogue: ComponentCatalogue): string => {
  const lines = [
    '# Component catalogue',
    '',
    '> Generated by `npm run catalogue:generate`. Do not edit by hand.',
    '',
    `This catalogue contains ${catalogue.components.length} discovered React components across ${catalogue.coverage.representedSources} source modules. ${catalogue.coverage.ignoredSources} eligible source modules are explicitly ignored.`,
    '',
    '| ID | Component | Source | Category | Layer | Lifecycle | Product area | Viewports | Workbench | Audits (a11y / i18n / theme) | Candidate family | Notes |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
  ]

  for (const component of catalogue.components) {
    const metadata = component.metadata
    lines.push(
      `| \`${component.id}\` | ${component.name} | \`${component.source}\` | ${metadata.category} | ${metadata.layer} | ${metadata.lifecycle} | ${metadata.productArea} | ${cell(metadata.viewportContexts)} | ${metadata.readiness.workbench} | ${metadata.readiness.accessibility} / ${metadata.readiness.internationalization} / ${metadata.readiness.theme} | ${metadata.candidateFamily ?? '—'} | ${cell(metadata.notes)} |`,
    )
  }

  lines.push('', '## Generated facts', '')
  for (const component of catalogue.components) {
    lines.push(
      `- **${component.name}** — declaration: ${component.declaration}; visibility: ${component.visibility}; exports: ${cell(exportLabel(component))}; consumers: ${cell(component.consumers.map((value) => `\`${value}\``))}; contexts: ${cell(component.dependencies.contexts)}; internal: ${cell(component.dependencies.internal.map((value) => `\`${value}\``))}; external: ${cell(component.dependencies.external.map((value) => `\`${value}\``))}`,
    )
  }

  lines.push('', '## Repeated inline pattern candidates', '')
  lines.push('> Similarity is not equivalence. These deterministic signals are review candidates only.', '')
  for (const candidate of catalogue.reviewCandidates) {
    lines.push(
      `### ${candidate.family}`,
      '',
      `${candidate.occurrences.length} occurrences; assessment: ${candidate.assessment}; equivalence: ${candidate.equivalence}.`,
      '',
    )
    for (const occurrence of candidate.occurrences) {
      const classes = occurrence.staticClassTokens.length > 0
        ? occurrence.staticClassTokens.map((token) => `\`${token}\``).join(', ')
        : 'none detected'
      lines.push(
        `- \`${occurrence.source}:${occurrence.line}:${occurrence.column}\` — owner \`${occurrence.ownerComponentId}\`; tag \`<${occurrence.tag}>\`; static classes: ${classes}; dynamic classes: ${occurrence.dynamicClasses ? 'yes' : 'no'}; equivalence: ${candidate.equivalence}.`,
      )
    }
    lines.push('')
  }

  lines.push('', '## Explicitly ignored sources', '')
  for (const ignored of catalogue.ignored) {
    lines.push(`- \`${ignored.source}\` — ${ignored.reason}`)
  }
  return `${lines.join('\n')}\n`
}
