import type {CatalogueComponent, ComponentCatalogue} from '../../src/types/componentCatalogue.types.ts'

const cell = (values: string[]): string => values.length > 0 ? values.join('<br>') : '—'

const exportLabel = (component: CatalogueComponent): string[] =>
  component.exports.map((item) => `${item.kind}: ${item.name} (${item.module})`)

export const renderManifest = (catalogue: ComponentCatalogue): string =>
  `${JSON.stringify(catalogue, null, 2)}\n`

export const renderMarkdown = (catalogue: ComponentCatalogue): string => {
  const lines = [
    '# Component catalogue',
    '',
    '> Generated by `npm run catalogue:generate`. Do not edit by hand.',
    '',
    `This initial catalogue slice contains ${catalogue.components.length} discovered React components.`,
    '',
    '| Component | Source | Declaration | Visibility | Exports | Consumers | Context dependencies |',
    '| --- | --- | --- | --- | --- | --- | --- |',
  ]

  for (const component of catalogue.components) {
    lines.push(
      `| ${component.name} | \`${component.source}\` | ${component.declaration} | ${component.visibility} | ${cell(exportLabel(component))} | ${cell(component.consumers.map((value) => `\`${value}\``))} | ${cell(component.dependencies.contexts)} |`,
    )
  }

  lines.push('', '## Module dependencies', '')
  for (const component of catalogue.components) {
    lines.push(
      `- **${component.name}** — internal: ${cell(component.dependencies.internal.map((value) => `\`${value}\``))}; external: ${cell(component.dependencies.external.map((value) => `\`${value}\``))}`,
    )
  }
  return `${lines.join('\n')}\n`
}
