export const remainingActiveCoverage = [
  { id: 'ui.0003', disposition: 'exempt', reason: 'Local app-shell composition is covered through its exported marketing sections.' },
  { id: 'ui.0007', disposition: 'story' },
  { id: 'ui.0008', disposition: 'story' },
  { id: 'ui.0020', disposition: 'story' },
  { id: 'ui.0023', disposition: 'story' },
  { id: 'ui.0025', disposition: 'story' },
  { id: 'ui.0031', disposition: 'story' },
  { id: 'ui.0032', disposition: 'story' },
  { id: 'ui.0072', disposition: 'story' },
  { id: 'ui.0129', disposition: 'story', owner: 'parent' },
  { id: 'ui.0130', disposition: 'story' },
  { id: 'ui.0131', disposition: 'story' },
  { id: 'ui.0133', disposition: 'story' },
  { id: 'ui.0136', disposition: 'story' },
  { id: 'ui.0139', disposition: 'exempt', reason: 'Private route-local card has no exported render seam.' },
  { id: 'ui.0140', disposition: 'exempt', reason: 'Host feedback route owns authenticated data fetching; its reusable feedback UI is catalogued directly.' },
  { id: 'ui.0148', disposition: 'exempt', reason: 'Authentication route redirects and mutates session state; its forms are catalogued by #33.' },
  { id: 'ui.0150', disposition: 'story' },
  { id: 'ui.0151', disposition: 'exempt', reason: 'Profile route owns authenticated mutations; ProfileHeader and form sections are catalogued directly.' },
  { id: 'ui.0154', disposition: 'exempt', reason: 'OAuth callback has no stable visual output beyond already catalogued loading and feedback patterns.' },
  { id: 'ui.0156', disposition: 'exempt', reason: 'Authentication callback is redirect infrastructure without standalone visual output.' },
] as const
